-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 10:45:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

SET @change_number = 1;
SET @version = "1.0";
SET @applied = CURRENT_TIMESTAMP();
SET @applied_by = "Matic Rašl";
SET @description = "1. verzija";
SET @file = "dbChanges_1.sql";

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Article` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Article` (
  `id` BINARY(16) NOT NULL,
  `EAN` VARCHAR(45) NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `cenaBrezDDV` FLOAT NOT NULL,
  `cenaZDDV` FLOAT NOT NULL,
  `DDV` FLOAT NOT NULL,
  `drzava` VARCHAR(45) NULL,
  `zaloga` INT NOT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Invoice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Invoice` (
  `id` BINARY(16) NOT NULL,
  `cenaZDDV` DOUBLE NOT NULL,
  `cenaBrezDDV` DOUBLE NOT NULL,
  `popust` DOUBLE NULL,
  `prodajalec` VARCHAR(45) NOT NULL,
  `podjetjeDavcniZavezanec` TINYINT NULL,
  `originalRacun` TINYINT NOT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Company` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `id` BINARY(16) NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `telSt` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `davcnaSt` INT NOT NULL,
  `maticnaSt` BIGINT NOT NULL,
  `davcniZavezanec` TINYINT NOT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Coupon` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Coupon` (
  `id` BINARY(16) NOT NULL,
  `tip` INT NOT NULL,
  `popust` DOUBLE NOT NULL,
  `EANIzdelka` VARCHAR(45) NULL,
  `EAN` VARCHAR(45) NOT NULL,
  `opis` VARCHAR(200) NOT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Article_Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Article_Invoice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Article_Invoice` (
  `id` BINARY(16) NOT NULL,
  `Article_idArticle` BINARY(16) NOT NULL,
  `Invoice_id` BINARY(16) NOT NULL,
  `kolicina` INT NOT NULL,
  PRIMARY KEY (`id`, `Article_idArticle`, `Invoice_id`),
  INDEX `fk_Article_Invoice_Article_idx` (`Article_idArticle` ASC),
  INDEX `fk_Article_Invoice_Invoice1_idx` (`Invoice_id` ASC),
  CONSTRAINT `fk_Article_Invoice_Article`
    FOREIGN KEY (`Article_idArticle`)
    REFERENCES `mydb`.`Article` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Article_Invoice_Invoice1`
    FOREIGN KEY (`Invoice_id`)
    REFERENCES `mydb`.`Invoice` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coupon_Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Coupon_Invoice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Coupon_Invoice` (
  `id` BINARY(16) NOT NULL,
  `Coupon_id` BINARY(16) NOT NULL,
  `Invoice_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`, `Coupon_id`, `Invoice_id`),
  INDEX `fk_Coupon_Invoice_Coupon1_idx` (`Coupon_id` ASC),
  INDEX `fk_Coupon_Invoice_Invoice1_idx` (`Invoice_id` ASC),
  CONSTRAINT `fk_Coupon_Invoice_Coupon1`
    FOREIGN KEY (`Coupon_id`)
    REFERENCES `mydb`.`Coupon` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Coupon_Invoice_Invoice1`
    FOREIGN KEY (`Invoice_id`)
    REFERENCES `mydb`.`Invoice` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SchemaVersion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SchemaVersion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SchemaVersion` (
  `idSchemaVersion` BINARY(16) NOT NULL,
  `change_number` INT NOT NULL,
  `version` VARCHAR(30) NOT NULL,
  `applied` DATETIME NOT NULL,
  `applied_by` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `file` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSchemaVersion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Invoice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Invoice` (
  `id` BINARY(16) NOT NULL,
  `cenaZDDV` DOUBLE NOT NULL,
  `cenaBrezDDV` DOUBLE NOT NULL,
  `popust` DOUBLE NULL,
  `prodajalec` VARCHAR(45) NOT NULL,
  `podjetjeDavcniZavezanec` TINYINT NULL,
  `originalRacun` TINYINT NOT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL,
  `modified` TIMESTAMP NULL,
  `podjetje_prodajalec` BINARY(16) NOT NULL,
  `podjetje_kupec` BINARY(16) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Invoice_Company1_idx` (`podjetje_prodajalec` ASC),
  INDEX `fk_Invoice_Company2_idx` (`podjetje_kupec` ASC),
  CONSTRAINT `fk_Invoice_Company1`
    FOREIGN KEY (`podjetje_prodajalec`)
    REFERENCES `mydb`.`Company` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Invoice_Company2`
    FOREIGN KEY (`podjetje_kupec`)
    REFERENCES `mydb`.`Company` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$

USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`Article_BEFORE_UPDATE` $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Article_BEFORE_UPDATE` BEFORE UPDATE ON `Article` FOR EACH ROW
BEGIN
	SET NEW.modified = CURRENT_TIMESTAMP();
END$$


USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`Company_BEFORE_UPDATE` $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Company_BEFORE_UPDATE` BEFORE UPDATE ON `Company` FOR EACH ROW
BEGIN
	SET NEW.modified = CURRENT_TIMESTAMP();
END$$


USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`Coupon_BEFORE_UPDATE` $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Coupon_BEFORE_UPDATE` BEFORE UPDATE ON `Coupon` FOR EACH ROW
BEGIN
	SET NEW.modified = CURRENT_TIMESTAMP();
END$$


USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`Invoice_BEFORE_UPDATE` $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Invoice_BEFORE_UPDATE` BEFORE UPDATE ON `Invoice` FOR EACH ROW
BEGIN
	SET NEW.modified = CURRENT_TIMESTAMP();
END$$

INSERT INTO SchemaVersion VALUES (UUID_TO_BIN(UUID()), @change_number, @version, @applied, @applied_by, @descrioption, @file);

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
